from . import product_category
from . import purchase_order
from . import product
from . import res_config_settings
from . import mail_compose_message
from . import res_partner
from . import mail_message
from . import mail_mail
from . import ir_ui_menu
